/*
 * This source file was generated by the Gradle 'init' task
 */
package edu.dam2.psp.eva1.ejercicios.sumatorio;

import static edu.dam2.psp.utiles.Funciones.lanzarPeticionLeerEntrada;

import java.util.Scanner;

public class Main
{
    public static void main(String[] args)
    {
        Scanner escaner = new Scanner(System.in);
        int limiteInf;
        int limiteSup;
        System.out.println("Calculo del sumatorio de enteros entre dos limites.\n");
        while (true)
        {
            try
            {
                limiteInf = Integer.parseInt(lanzarPeticionLeerEntrada(escaner, "Primer limite: "));
                limiteSup = Integer.parseInt(lanzarPeticionLeerEntrada(escaner, "Segundo limite: "));
                break;
            }
            catch (NumberFormatException nfe)
            {
                System.out.println("Alguno de los inputs no era un numero entero.");
            }
            catch (Exception e)
            {
                System.out.println("Error inesperado.");
            }
        }
        System.out.println("Sumatorio: " + Sumador.sumatorioDeIntervalo(limiteInf, limiteSup));
        System.exit(0);
    }
}
