/*
 * This source file was generated by the Gradle 'init' task
 */
package psp.ejercicios.sumatorio;

public class Main
{
    public static void main(String[] args)
    {
        try
        {
            if (args.length == 0)
                throw new IllegalArgumentException("No has pasado ningún argumento.");

            if (args.length != 2)
                throw new IllegalArgumentException("Este programa solo se ejecuta al recibir 2 argumentos.");

            boolean arg1EsDigito = args[0].matches("[+-]?\\d+");
            boolean arg2EsDigito = args[0].matches("[+-]?\\d+");

            if (!arg1EsDigito || !arg2EsDigito)
                throw new NumberFormatException("El argumento pasado no es un número entero.");

            int limiteInf = Integer.parseInt(args[0]);
            int limiteSup = Integer.parseInt(args[1]);
            System.out.println(Sumador.sumatorioDeIntervalo(limiteInf, limiteSup));
        }
        catch (Exception e)
        {
            e.printStackTrace();
            System.exit(-1);
        }
    }
}
