/*
 * This source file was generated by the Gradle 'init' task
 */
package psp.ejercicios.sumatorio;

public class Main
{
    public static void main(String[] args)
    {
        if (args.length == 0)
        {
            System.out.println("No has pasado ningún argumento.");
            System.exit(-20);
        }
        if (args.length != 2)
        {
            System.out.println("Este programa solo se ejecuta al recibir 2 argumentos.");
            System.exit(-21);
        }
        try
        {
            int limiteInf = Integer.parseInt(args[0]);
            int limiteSup = Integer.parseInt(args[1]);
            System.out.println(Sumador.sumatorioDeIntervalo(limiteInf, limiteSup));
        }
        catch (NumberFormatException nfe)
        {
            System.out.println("Alguno de los 2 argumentos pasados no es un numero entero.");
            System.exit(-30);
        }
        catch (IllegalArgumentException iae)
        {
            System.out.println("El segundo número tiene que ser mayor que el primero.");
            System.exit(-31);
        }
    }
}
